apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-web
  template:
    metadata:
      labels:
        app: workshop-web
    spec:
      containers:
      - name: app
        image: graillus/workshop-kubernetes:app-stateful
        ports:
        - containerPort: 3000
        env:
        - name: FILE_STORAGE_PATH
          value: /data/files
        # mount volume at given path
        volumeMounts:
        - name: storage # references the volume declared below
          mountPath: /data/files/uploads
      volumes:
      # The "storage" volume will contain uploaded files from users
      - name: storage
        emptyDir: {} # emptyDir will store files in a random location on the host disk.
