kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-persistent-volumeclaim
spec:
  storageClassName: pv-workshop
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
