apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "workshop-app.fullname" . }}
  labels:
    {{- include "workshop-app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
spec:
  rules:
    - host: app.k8s-workshop.eleven-labs.com
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ include "workshop-app.fullname" . }}
            servicePort: 8080
