apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "workshop-app.fullname" . }}
  labels:
    {{- include "workshop-app.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: 'localhost'
      http:
        paths:
        - path: /
          backend:
            serviceName: my-app
            servicePort: 8080
        - path: /my-other-app/
          backend:
            serviceName: my-other-app
            servicePort: 8080
