apiVersion: v1
kind: Service
metadata:
  name: {{ include "workshop-app.fullname" . }}
  labels:
    {{- include "workshop-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "workshop-app.selectorLabels" . | nindent 4 }}
  type: NodePort
  ports:
  - port: 8080
    targetPort: 3000
    protocol: TCP
