---
apiVersion: v1
kind: Service
metadata:
  name: my-exposed-service
spec:
  type: NodePort
  ports:
    - name: default
      port: 15672
      targetPort: stats
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: rabbitmq
---
## uncomment this only if aws-alb-ingress-controller is deployed
## do not forget to replace <replace-me> with your custom name
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: my-ingress
#  annotations:
#    kubernetes.io/ingress.class: alb
#    alb.ingress.kubernetes.io/scheme: "internet-facing"
#    # this certificate should already be deployed in ACM
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-3:598969483380:certificate/7254ff7b-c88a-4621-843a-2dcf84841500
#    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
#    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
#spec:
#  rules:
#    - host: <replace-me>.k8s-workshop.eleven-labs.com
#      http:
#        paths:
#         - path: /*
#           backend:
#             serviceName: ssl-redirect
#             servicePort: use-annotation
#         - path: /*
#           backend:
#             serviceName: my-exposed-service
#             servicePort: default
#
